apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: abderrazakbouasker/expense-tracker
        ports:
        - containerPort: 80

